# Generated by Django 5.2.1 on 2025-05-23 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito_de_compras', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='creado',
            new_name='fecha_pedido',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='descripcion',
            new_name='cantidad_pedido',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_fab',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_ven',
        ),
    ]
