# Generated by Django 5.2.1 on 2025-05-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='descripcionRol',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='reportes',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Aprendiz', 'Aprendiz'), ('Instructor', 'Instructor'), ('Administrador', 'Administrador'), ('Personal de mantenimiento', 'Personal de mantenimiento')], default='Aprendiz', help_text='Define el nivel de acceso del usuario', max_length=25),
        ),
        migrations.DeleteModel(
            name='DescripcionRol',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
