# Generated by Django 5.2.3 on 2025-06-21 18:46

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_rol_descripcionrol_remove_rol_reportes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='CO'),
        ),
    ]
