# Generated by Django 5.2.1 on 2025-05-19 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Detalle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_creacion', models.DateField()),
                ('Detalle', models.CharField(max_length=100)),
                ('Evidencia', models.ImageField(blank=True, null=True, upload_to='evidencias')),
                ('Ubicacion', models.CharField(max_length=100)),
                ('Tipo', models.CharField(max_length=100)),
                ('Estado_Reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.estado_reporte')),
            ],
        ),
    ]
