# Generated by Django 5.2.1 on 2025-05-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes',
            name='Estado_Reporte',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Solucionado', 'Solucionado')], default='Pendiente', help_text='Define en que estado se encuentra el reporte', max_length=15),
        ),
        migrations.DeleteModel(
            name='Estado_Reporte',
        ),
    ]
