# Generated by Django 5.2.1 on 2025-05-23 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='descripcion',
            new_name='detalles',
        ),
    ]
